commands:
  - option:
      caption: Create/Append Note
      classifications:
        - category
        - group
      ignore:
        - Reports
      max_cols: 4
      templates:
        - template: ./templates/_default.md
          tokens:
            - title
            - datetime
        - template: ./templates/meeting_notes.md
          paths:
            - /FY23
          tokens:
            - title
            - datetime
        - template: ./templates/development_notes.md
          paths:
            - /Personal Development
          tokens:
            - title
            - datetime
working_directory: