working_directory:
templates:
  - template: ./templates/_default.md
    tokens:
      - title
      - datetime
  - template: ./templates/meeting_notes.md
    paths:
      - /FY22 MFG
      - /FY23 MAE
    tokens:
      - title
      - datetime
  - template: ./templates/development_notes.md
    paths:
      - /Personal Development
    tokens:
      - title
      - datetime
  - template: ./templates/one_on_one_notes.md
    paths:
      - /Personal Development/1 on 1s
    tokens:
      - title
      - datetime
note_exclusion_folders:
  - Reports
commands:
  - Create/Append Note
  - Run Fiscal Year Oppty Report
  - Run Fiscal Quarter Oppty Report
  - Run Personal Development Report
classifications:
  - category
  - group
max_cols: 4