working_directory:
templates:
  - template: ./templates/_default.md
    tokens:
      - title
      - datetime
  - template: ./templates/meeting_notes.md
    paths:
      - /FY23
    tokens:
      - title
      - datetime
  - template: ./templates/development_notes.md
    paths:
      - /Personal Development
    tokens:
      - title
      - datetime
note_exclusion_folders:
  - Reports
commands:
  - Create/Append Note
classifications:
  - category
  - group
max_cols: 4